# Generated by Django 5.1.4 on 2025-01-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='status',
            new_name='jira_status',
        ),
    ]
