# Generated by Django 5.1.4 on 2025-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_status_document_jira_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clarifying_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='scope_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='jira_status',
            field=models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed'), ('PUSHED', 'Pushed'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='UNPROCESSED', max_length=20),
        ),
    ]
